# Generated by Django 4.2.1 on 2023-05-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test0", "0004_alter_user_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="superuser",
            field=models.BooleanField(default=False),
        ),
    ]
