# Generated by Django 4.2.1 on 2023-06-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test0", "0006_remove_user_superuser_alter_user_is_superuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="diesease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("descript", models.TextField()),
            ],
        ),
    ]
